# Generated by Django 4.1.13 on 2025-11-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_devotee_photo_url_alter_devotee_sabha_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotee',
            name='sabha_type',
            field=models.CharField(choices=[('bal', 'Bal Sabha'), ('yuvak', 'Yuvak Sabha'), ('mahila', 'Mahila Sabha'), ('sanyukt', 'Sanyukt Sabha')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sabha',
            name='sabha_type',
            field=models.CharField(choices=[('bal', 'Bal Sabha'), ('yuvak', 'Yuvak Sabha'), ('mahila', 'Mahila Sabha'), ('sanyukt', 'Sanyukt Sabha')], max_length=20),
        ),
    ]
