# Generated by Django 5.2.8 on 2025-11-19 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_devotee_devotee_id_devotee_devotee_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sabha',
            name='mandal',
            field=models.CharField(default='Default Mandal', max_length=100),
        ),
        migrations.AddField(
            model_name='sabha',
            name='xetra',
            field=models.CharField(default='Default Xetra', max_length=100),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_sabha_types', models.JSONField(default=list, help_text='Sabha types this user can access')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
